steps:
    - name: 'bash'
      args: ['ls']
    - name: 'gcr.io/cloud-builders/docker'
      args:
      - build
      - "--tag=gcr.io/$PROJECT_ID/node-app:$SHORT_SHA"
      - "--file=./CloudBuild/InstanceGroupRollingUpdate/Dockerfile"
      - .
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/node-app:$BUILD_ID']
