steps:
    - name: 'gcr.io/cloud-builders/docker'
      args:
      - build
      - "--tag=gcr.io/$PROJECT_ID/node-app:$SHORT_SHA"
      - "--file=./CloudBuild/InstanceGroupRollingUpdate/Dockerfile"
      - .
    - name: 'bash'
      args: 
      - '$(date -u +%Y-%m-%d-%H-%M)'


#     - name: 'gcr.io/cloud-builders/docker'
#       args: ['push', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA']
    
#     images: ['gcr.io/$PROJECT_ID/node-app:$SHORT_SHA']
